### PR TITLE
Add files for Mulliken tests in stdout-charges

### PR DESCRIPTION
**Pull request by ahkole**
This PR adds files necessary for testing the parsing of the Mulliken charges in `stdoutSileSiesta`. See also https://github.com/zerothi/sisl/pull/691

### CODE REVIEW

**Comment by ahkole** [comment]
Please note btw that I chose to add the writing of the Mulliken charges to the output files that were already there for the Hirshfeld and Voronoi charges. This means that, in principle, the tests for those charges could be adapted to use these files instead of the old ones (which then could deleted). If this is undesirable I could also update these output files to only write the Mulliken charges.

**Review by zerothi — CHANGES_REQUESTED** [review]
If you don't mind, then I would suggest each run, gets a separate folder. That would enable one to subsequently add the `DM` files to cross-reference the charges.

If you think this is a waste now, I will probably do it in some time.

**Comment by ahkole** [comment]
I've moved the files for each different run into its own subfolder. Is it still sufficient to have a single `README.md` at the top of the file tree, since all the runs are variants of each other with one or two parameters changed? Would you also like me to add DM files for each of the runs? Or is that for a future development?

**Comment by zerothi** [comment]
> I've moved the files for each different run into its own subfolder. Is it still sufficient to have a single `README.md` at the top of the file tree, since all the runs are variants of each other with one or two parameters changed? Would you also like me to add DM files for each of the runs? Or is that for a future development?

It would be nice if you could add DM and 1 file which contains the overlap matrices, in that way we can double check the results from siesta, and from sisl ;)

**Comment by ahkole** [comment]
> It would be nice if you could add DM and 1 file which contains the overlap matrices, in that way we can double check the results from siesta, and from sisl ;)

Maybe I could instead add the main netCDF output file (`SystemLabel.nc`)? That would contain both the DM and the overlap matrices, right? Or would it be preferable to have the separate DM file?

**Comment by zerothi** [comment]
The netcdf files would be great! Consider using the compression for minimal disk space, remember to update the input fdf files!

**Comment by ahkole** [comment]
I tried storing the `SystemLabel.nc` by setting `CDF.Save t` in the input files but I wasn't getting any netCDF files. After checking the documenation I discovered the following sentence `NOTE: this option is not available for MD/relaxations, only for force constant runs.` and since all the tests were relaxations that explained why I wasn't getting the main netCDF file. Instead I have now used `Write.DMHS.History.NetCDF` to write a DMHS file for every geometry step. These nc files were compressed afterward with `nccopy`. Do we have enough information if for each run there is a DMHS netCDF file for every geometry step?

**Comment by zerothi** [comment]
Yes, i think so, lets do this. This actually opens up a new issue with `sisl`, it doesn't implement the `DMHS.nc` file format. But, not a blocker now!

Thanks!

**Pull request merged**
