### PR TITLE
Add vibra test files

### PR DESCRIPTION
**Pull request by nils-wittemeier**

### CODE REVIEW

**Comment by zerothi** [comment]
How is it, is this all that is necessary? No other files, no secondary fdf files for the runs?

**Comment by nils-wittemeier** [comment]
This is all that's needed to test the reading, it is not sufficient to create the input files.

**Comment by zerothi** [comment]
> This is all that's needed to test the reading, it is not sufficient to create the input files.

No, it was more, what is needed to create the full output, is the input fdf all that is required? I am in the process of re-doing the tests repo #14 , I am pretty far, but it would be great if this can just be runned, without doing anything ;)
So, is there anything that is missing to fully reproduce the `*.vectors` file? If not, then fine, I just can't recall if anything needs to be done?

**Comment by nils-wittemeier** [comment]
Okay... I used a different way of generating the force constant files ...

But I can create the necessary SIESTA input files, or change the example ... 

I have everything that's needed for a simple hydrogen chain SZ basis. I think I'll just change it to that and add all necessary files to reproduce the inputs.

**Comment by zerothi** [comment]
that would be great, a simple thing, with all that is necessary to reproduce, then I'll work through it soonish ;)

**Comment by nils-wittemeier** [comment]
Okay I updated the example. Is this what you had in mind?

**Comment by zerothi** [comment]
Yes, this is fine.

**Pull request merged**
