### PR TITLE
Separate directories for ORCA files

### PR DESCRIPTION
**Pull request by tfrederiksen**
I suggest to reorganize the orca files into separate directories for each system/calculation.

I'll prepare a separate PR for sisl after this gets in.

### CODE REVIEW

**Comment by tfrederiksen** [comment]
Shall I include this change in https://github.com/zerothi/sisl/pull/722 or as a separate PR?

**Comment by zerothi** [comment]
Separate, please :)

**Comment by tfrederiksen** [comment]
OK :)

**Comment by zerothi** [comment]
Thanks @tfrederiksen, I already transitioned in `sisl` the directories!

**Comment by zerothi** [comment]
@tfrederiksen I am currently working on #14, I am getting nearer the end ;)
However, I don't know how to run orca stuff, could you provide some details on how to run orca, and also, the necessary input files for the 3 tests?

**Comment by tfrederiksen** [comment]
Sorry, I lost track of these threads. I'll try to localize the inputs and get back to you over the next days.

**Comment by zerothi** [comment]
Thanks!

**Pull request merged**
